/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    companies: Company;
    events: Event;
    leadership: Leadership;
    priorities: Priority;
    capitalTiers: CapitalTier;
    industryTiers: IndustryTier;
    benefits: Benefit;
    hubs: Hub;
    counties: County;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    priorities: PrioritiesSelect<false> | PrioritiesSelect<true>;
    capitalTiers: CapitalTiersSelect<false> | CapitalTiersSelect<true>;
    industryTiers: IndustryTiersSelect<false> | IndustryTiersSelect<true>;
    benefits: BenefitsSelect<false> | BenefitsSelect<true>;
    hubs: HubsSelect<false> | HubsSelect<true>;
    counties: CountiesSelect<false> | CountiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  kind: 'capital' | 'industry';
  /**
   * Capital only: Fund, Angel network, Family Office, CVC. Leave blank for industry members.
   */
  type?: string | null;
  /**
   * Industry only: Spirits & Beverage, Healthcare, etc.
   */
  sector?: string | null;
  city: string;
  state?: string | null;
  note?: string | null;
  /**
   * URL — full https:// link.
   */
  website?: string | null;
  displayOrder?: number | null;
  /**
   * Show on the home-page founding coalition strip.
   */
  featuredOnHome?: boolean | null;
  county?: (number | null) | County;
  /**
   * Polymorphic — capital members link to capitalTiers, industry to industryTiers.
   */
  tier?:
    | ({
        relationTo: 'capitalTiers';
        value: number | CapitalTier;
      } | null)
    | ({
        relationTo: 'industryTiers';
        value: number | IndustryTier;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counties".
 */
export interface County {
  id: number;
  name: string;
  hub?: (number | null) | Hub;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs".
 */
export interface Hub {
  id: number;
  name: string;
  description?: string | null;
  leadOrganizer?: (number | null) | Member;
  /**
   * Which Kentucky counties feed into this hub.
   */
  counties?: (number | County)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capitalTiers".
 */
export interface CapitalTier {
  id: number;
  name: string;
  /**
   * e.g. '$50 / yr', '$250 / yr + $50 each add'l professional', 'By invitation'.
   */
  dues?: string | null;
  /**
   * e.g. '1.5×', '1×'.
   */
  voting?: string | null;
  /**
   * e.g. 'Eligible'.
   */
  board?: string | null;
  dealFlow?: ('standard' | 'priority' | 'lead') | null;
  firmDisplay?: ('yes' | 'no') | null;
  /**
   * Footnote indicator like '*' if this tier has an attached footnote.
   */
  footnoteAnchor?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industryTiers".
 */
export interface IndustryTier {
  id: number;
  name: string;
  dues?: string | null;
  /**
   * e.g. 'All sectors', 'Up to 3 sectors', '1 sector'.
   */
  sectorBriefings?: string | null;
  pilotPathways?: ('standard' | 'priority') | null;
  summitAccess?: ('reserved' | 'general') | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  description?: string | null;
  sector?: string | null;
  city?: string | null;
  state?: string | null;
  /**
   * URL — full https:// link.
   */
  website?: string | null;
  /**
   * Show on home-page 'Real founders. Real products.' strip.
   */
  featured?: boolean | null;
  /**
   * Capital members that backed this company.
   */
  backedBy?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  city: string;
  state?: string | null;
  audience: 'capital' | 'industry' | 'both' | 'public';
  description: string;
  /**
   * Hero treatment on the events page (next upcoming featured event).
   */
  featured?: boolean | null;
  /**
   * URL — registration link.
   */
  rsvpUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  /**
   * KPCA-specific role, e.g. 'Founding Chair, KPCA'.
   */
  kpcaRole?: string | null;
  /**
   * Title at their firm: 'Managing Partner', 'VP', 'Founder'.
   */
  externalRole?: string | null;
  /**
   * Firm name (or 'To be elected — June 2026' for placeholders).
   */
  affiliation?: string | null;
  bio?: string | null;
  group: 'officers' | 'board' | 'open-seats';
  displayOrder?: number | null;
  /**
   * Marks placeholder entries (member-elected seats, TBA counsel, etc.).
   */
  isOpenSeat?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priorities".
 */
export interface Priority {
  id: number;
  headline: string;
  body: string;
  /**
   * Chip label, e.g. 'Legislative · 2027 cycle'.
   */
  tag?: string | null;
  /**
   * Numbering shown as 01 / 02 / 03 / 04 — derived from this field.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benefits".
 */
export interface Benefit {
  id: number;
  kind: 'capital' | 'industry';
  label: string;
  body: string;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'priorities';
        value: number | Priority;
      } | null)
    | ({
        relationTo: 'capitalTiers';
        value: number | CapitalTier;
      } | null)
    | ({
        relationTo: 'industryTiers';
        value: number | IndustryTier;
      } | null)
    | ({
        relationTo: 'benefits';
        value: number | Benefit;
      } | null)
    | ({
        relationTo: 'hubs';
        value: number | Hub;
      } | null)
    | ({
        relationTo: 'counties';
        value: number | County;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  type?: T;
  sector?: T;
  city?: T;
  state?: T;
  note?: T;
  website?: T;
  displayOrder?: T;
  featuredOnHome?: T;
  county?: T;
  tier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  sector?: T;
  city?: T;
  state?: T;
  website?: T;
  featured?: T;
  backedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  city?: T;
  state?: T;
  audience?: T;
  description?: T;
  featured?: T;
  rsvpUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  kpcaRole?: T;
  externalRole?: T;
  affiliation?: T;
  bio?: T;
  group?: T;
  displayOrder?: T;
  isOpenSeat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priorities_select".
 */
export interface PrioritiesSelect<T extends boolean = true> {
  headline?: T;
  body?: T;
  tag?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capitalTiers_select".
 */
export interface CapitalTiersSelect<T extends boolean = true> {
  name?: T;
  dues?: T;
  voting?: T;
  board?: T;
  dealFlow?: T;
  firmDisplay?: T;
  footnoteAnchor?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industryTiers_select".
 */
export interface IndustryTiersSelect<T extends boolean = true> {
  name?: T;
  dues?: T;
  sectorBriefings?: T;
  pilotPathways?: T;
  summitAccess?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benefits_select".
 */
export interface BenefitsSelect<T extends boolean = true> {
  kind?: T;
  label?: T;
  body?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs_select".
 */
export interface HubsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  leadOrganizer?: T;
  counties?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counties_select".
 */
export interface CountiesSelect<T extends boolean = true> {
  name?: T;
  hub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}